# Generated by Django 4.2.2 on 2023-08-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('employee_code', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_designation', models.CharField(max_length=50)),
                ('employee_contact', models.CharField(max_length=10)),
                ('employee_image', models.FileField(blank=True, null=True, upload_to='images/employeeImage')),
            ],
            options={
                'db_table': 'employee_details',
                'ordering': ['-employee_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('office_time', models.DurationField()),
                ('break_hour', models.DurationField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employeedetail')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-date', 'entry_time'],
            },
        ),
    ]
