# Generated by Django 4.2.2 on 2023-08-03 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_department_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department_name',
                'ordering': ['-employee_department_name'],
            },
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='employee_designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employeedepartment'),
        ),
    ]
