# Generated by Django 4.2.2 on 2023-08-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_employeedepartment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedepartment',
            options={'ordering': ['-department_name']},
        ),
        migrations.RenameField(
            model_name='employeedepartment',
            old_name='employee_department_name',
            new_name='department_name',
        ),
    ]
