# Generated by Django 4.2.2 on 2023-08-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_alter_employeedepartment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employeedetail')),
            ],
            options={
                'db_table': 'designation_name',
                'ordering': ['-employee_designation'],
            },
        ),
    ]
