# Generated by Django 4.2.2 on 2023-08-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_employeedesignation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedesignation',
            options={'ordering': ['-designation_name']},
        ),
        migrations.RenameField(
            model_name='employeedesignation',
            old_name='employee_designation',
            new_name='designation_name',
        ),
        migrations.AlterModelTable(
            name='employeedesignation',
            table='employee_designation',
        ),
    ]
