# Generated by Django 4.2.2 on 2023-08-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0005_alter_employeedesignation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedesignation',
            name='designation_name',
            field=models.CharField(max_length=100),
        ),
    ]
