# Generated by Django 4.2.2 on 2023-08-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0007_alter_employeedetail_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
