# Generated by Django 4.2.2 on 2023-09-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0008_employeedetail_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='employee_code',
            field=models.PositiveIntegerField(),
        ),
    ]
