# Generated by Django 4.2.2 on 2023-11-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0008_employeedetail_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='employee_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='employee_image',
            field=models.FileField(blank=True, null=True, upload_to='images/employeeImage/'),
        ),
    ]
