# Generated by Django 4.2.2 on 2023-09-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0012_remove_employeedetail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='employee_code',
            field=models.PositiveIntegerField(),
        ),
    ]
