# Generated by Django 4.2.2 on 2023-09-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0013_employeedetail_id_alter_employeedetail_employee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='employee_code',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
