# Generated by Django 4.2.2 on 2023-11-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignproject',
            name='assigned_date',
            field=models.DateTimeField(),
        ),
    ]
